### PR TITLE
Fixed video in skal's post

### PR DESCRIPTION
**Pull request by nihal111**
Removed custom style attributes in place of css class `video-container`.

### CODE REVIEW

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net/splashsite/pull/82 :rocket:

**Comment by nihal111** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net/splashsite/pull/82 :rocket:

**Comment by nihal111** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net/splashsite/pull/82 :rocket:

**Comment by nihal111** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net/splashsite/pull/82 :rocket:

**Pull request merged**
