### PR TITLE
Fixes #31. Player with Terasology OST

### LINKED ISSUE #31: Add optional music to site featuring ChrisK's soundtrack
Not enabled by default, of course, since everybody loves automatic HTML music amirite?

Probably a little note icon somewhere that turns it on and off, if not showing/hiding a tiny media player probably including a link to the soundtrack somewhere else.

Would also be handy for a static display of Terasology at possible future events ... ;-)

### PR DESCRIPTION
**Pull request by neoascetic**
Hey! I have a little surprise for you guys! Demo is [there](http://neoascetic.me/terasology.org/), take a look in the top left corner!

You need to enable flash on this site if you want to hear something. SoundManager2 supports HTML5, however. Maybe I'll fix it later.

Waiting for comments and suggestions.

### CODE REVIEW

**Comment by neoascetic** [comment]
Ping #31

**Comment by Cervator** [comment]
Nice! That looks very subtle and smooth, turned on right away in my firefox, no loading time at all!

I was curious what would happen on my Android phone, and it loads the tiny little run button and even allowed me to tap it, then switched to the playing look, although actually started playing since I guess Flash no worky there. But it didn't pop up any kind of angry warning, which is what I was looking for :-)

Anybody got an iOS device to see how that handles it? If no angry warning we can probably merge as is and see about HTML5 later

Track selection is random? My FF got Menu Theme, Android got Peaceful World

Only tricky part I can think of is having a background with pure white in that part of the screen, but really then you can just wait till it switches. Or maybe toss a black outline around the text if that's easy?

**Comment by nnsdev** [comment]
Could you make it more visible? I needed a bit to find that :D

**Comment by Cervator** [comment]
I kinda like having it tiny, but maybe it would be an idea to change the background lineup so it would start with a screenshot with a darker background in the top left? :-)

**Comment by neoascetic** [comment]
After adding shadow to player text it seems to be more visible on white background, so I'm merging this.

Tracks played randomly from specified SoundCloud playlist (currently it is Terasology Volume 1), feel free to change it.

**Comment by Cervator** [comment]
Excellent, the bit of shadowing makes a big difference. Thanks :-)

**Pull request merged**
