### PR TITLE
Fixes #7

### LINKED ISSUE #7: Make the social buttons highlight into colored versions like in the launcher?
The social buttons on https://github.com/MovingBlocks/TerasologyLauncher currently light up into colored versions when hovered over. It would be ideal if we use the exact same passive/active social icons in both places :-)

### PR DESCRIPTION
**Pull request by neoascetic**

### CODE REVIEW

**Comment by nnsdev** [comment]
Thanks for the PR. I'll check this and merge this when everything works :)

**Comment by nnsdev** [comment]
Okay, very good. Thanks! Merged!

**Comment by Cervator** [comment]
Thanks again, @neoascetic !

You seem quite on top of this so I've gone ahead and added you to our splash site team so you can push directly if you like. Feel free to still use PRs whenever we need to review/test - but this way tiny tweaks are easy to submit :-)

**Comment by nnsdev** [comment]
Heh, you're showing me that I also have to learn things, especially the new HTML5/CSS3 features, I'm outdated :-D

**Pull request merged**
