### PR TITLE
Add myself to mentor list

### PR DESCRIPTION
**Pull request by rzats**
👍

### CODE REVIEW

**Comment by rzats** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net/splashsite/pull/98 :rocket:

**Comment by rzats** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net/splashsite/pull/98 :rocket:

**Comment by rzats** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net/splashsite/pull/98 :rocket:

**Pull request merged**
