### PR TITLE
Added blog post about GCI with Tiled and my mentor entry

### PR DESCRIPTION
**Pull request by bjorn**

### CODE REVIEW

**Comment by syntaxi** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net/splashsite/pull/102 :rocket:

**Comment by smsunarto** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net/splashsite/pull/102 :rocket:

**Comment by bjorn** [comment]
Thanks. :-)

**Pull request merged**
