### PR TITLE
Switch to our new font, make link more secure. 

### PR DESCRIPTION
**Pull request by MarkDerosier**
for consistancy, and potental legal reasons, the Minecraftia font has been replaced with the Notosans font. 

A link has been made to default to https: for security/good practice reasons.

### CODE REVIEW

**Comment by MarkDerosier** [comment]
Removed blog icon from site. Blog is never used or updated.

**Comment by msteiger** [comment]
Looks good to me. It there a way to preview the final website?

Potential follow-up: use the new button background images

**Comment by Cervator** [comment]
Finally got a chance to check this out.

For testing I usually just grab the whole repo via the zip link, then upload it to my webhost somewhere like http://nanoware.org/terasology/splash/

Weirdly the social/tool icons aren't working right that way, but I figure that can't be breaking from this PR. In Firefox the icons only show up when I hover over them and are otherwise invisible. In Chrome they're just always visible in their "activated state"

Unless somehow the changing of the `normalize.min.css` link is involved? Does it look the same for either of you via the test URL?

As for tweaking the PR our project font is admittedly a little more boring. It also doesn't quite fit as well in the buttons, which were sized for the larger font. @chessandgo would you mind either tweaking the text size to fit the buttons or shrink the buttons a little to fit the text? Maybe it could just be aligned inside the buttons, the text is glued to the top of the buttons for me.

Logo-wise maybe we could put the forum header logo in instead of the plain text logo?

forumlogo

**Comment by msteiger** [comment]
Good work! The button text doesn't look right to me though (Chrome)

image

**Comment by Cervator** [comment]
Yep I noted that with @MarkDerosier on IRC once or twice. I figured it wasn't a blocker.

Submitted #59 for a later fix :-)

**Pull request merged**
