### PR TITLE
Overview Post for GSOC 2019

### PR DESCRIPTION
**Pull request by skaldarnar**

### CODE REVIEW

**Comment by smsunarto** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net/splashsite/pull/126 :rocket:

**Comment by smsunarto** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net/splashsite/pull/126 :rocket:

**Comment by dave2s** [comment]
>AndyTechGuy will make this idea come to **live** in an initial world implementation

This a typo?

**Pull request merged**
