### PR TITLE
Added Official Blog Post for Lost Exploration World

### PR DESCRIPTION
**Pull request by nihal111**
Draft of the official blog post for the Lost Exploration World project under GSoC '17.

### CODE REVIEW

**Comment by Cervator** [comment]
Read through it, pretty good :-)

Yeah it gets a bit long'ish, which is certainly something I'm familiar with myself ;-) I have to catch myself and spot places where I get too caught up in details where ideal state should be brief. A good example here might be when you introduce what will be a "gist" of the lore and it could have served as a preface to a novel :D

There are a few spots like that you could edit a bit to cut out some non-essentials, but it isn't particularly critical, so that's up to you. Looking forward to seeing it in full blog form glory! Maybe we can aim to publish Friday or early Saturday?

**Comment by nihal111** [comment]
Let's preview this
Testing for preview on http://preview.terasology.net/

**Comment by nihal111** [comment]
Let's preview this
Testing for preview on http://preview.terasology.net/

**Comment by Cervator** [comment]
Testing out the Let's preview this thing :D

**Comment by nihal111** [comment]
test

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net :shipit:

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net :rocket:

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net :rocket:

**Comment by nihal111** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net :rocket:

**Comment by nihal111** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net/splashsite/pull/81 :rocket:

**Comment by nihal111** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net/splashsite/pull/81 :rocket:

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net/splashsite/pull/81 :rocket:

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net/splashsite/pull/81 :rocket:

**Comment by nihal111** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net/splashsite/pull/81 :rocket:

**Comment by nihal111** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net/splashsite/pull/81 :rocket:

**Pull request merged**
