### PR TITLE
Fixed overflowing images

### PR DESCRIPTION
**Pull request by TheFlash98**
This fixes the overflowing images by setting maximum width to 100%.
Thanks to @nihal111.

### CODE REVIEW

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://prev.terasology.net/splashsite/pull/85 :rocket:

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by nihal111** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://prev.terasology.net/splashsite/pull/85 :rocket:

**Comment by nihal111** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://prev.terasology.net/splashsite/pull/85 :rocket:

**Comment by nihal111** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://prev.terasology.net/splashsite/pull/85 :rocket:

**Comment by nihal111** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://prev.terasology.net/splashsite/pull/85 :rocket:

**Comment by nihal111** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net/splashsite/pull/85 :rocket:

**Pull request merged**
