### PR TITLE
Add myself

### PR DESCRIPTION
**Pull request by SkySom**
Cause I'm awesome

### CODE REVIEW

**Comment by smsunarto** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net/splashsite/pull/97 :rocket:

**Comment by SkySom** [comment]
Let's preview this

**Comment by gooey-splashsite** [comment]
Preview is available on http://preview.terasology.net/splashsite/pull/97 :rocket:

**Pull request merged**
